name: Jampa Ruby
description: Comunidade de desenvolvedores Ruby/Rails de João Pessoa
meta_description: "Comunidade de ruby"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: "/JampaRuby"
url: "https://giovannycordeiro.github.io"
domain_name: "yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: ""

# Disqus config
disqus-shortname: ""
